Repository cirope/mawidabp, pull requests merged in 2018-06, with the labels that each got.

#74 New question yes/no option
  Gemfile.lock
  app/controllers/concerns/polls/reports.rb
  app/controllers/polls/questionnaires_controller.rb
  app/helpers/polls_helper.rb
  app/helpers/questionnaires_helper.rb
  app/models/answer_yes_no.rb
  app/models/concerns/answers/validations.rb
  app/models/concerns/questionnaires/answers.rb
  app/models/concerns/questions/callbacks.rb
  app/models/concerns/questions/constants.rb
  app/models/concerns/questions/options.rb
  app/models/concerns/questions/scopes.rb
  app/models/question.rb
  app/models/questionnaire.rb
  app/pdfs/polls/answer_pdf.rb
  app/pdfs/polls/business_unit_pdf.rb
  app/pdfs/polls/pdf_columns.rb
  app/pdfs/polls/pdf_headers.rb
  app/pdfs/polls/pdf_scores.rb
  app/pdfs/polls/questionnaire_pdf.rb
  app/views/polls/_answer.html.erb
  app/views/polls/answers/index.html.erb
  app/views/polls/business_units/index.html.erb
  app/views/polls/questionnaires/index.html.erb
  app/views/polls/show.html.erb
  app/views/questionnaires/_form.html.erb
  app/views/questionnaires/_question.html.erb
  config/locales/application.es.yml
  config/locales/es.yml
  config/locales/models.es.yml
  config/locales/views.es.yml
  db/migrate/20120528180903_create_answers.rb
  db/schema.rb
  test/controllers/polls_controller_test.rb
  test/controllers/questionnaires_controller_test.rb
  test/fixtures/answers.yml
  test/fixtures/questions.yml
  test/models/poll_test.rb
  test/models/questionnaire_test.rb
Labels: improvement

#70 LDAP Importer mailer
  app/mailers/ldap_mailer.rb
  app/models/concerns/organizations/scopes.rb
  app/views/common_mailer/_footer.html.erb
  app/views/ldap_mailer/import_notifier.html.erb
  app/views/notifier_mailer/_footer.html.erb
  app/views/notifier_mailer/blank_password_notification.html.erb
  app/views/notifier_mailer/changes_notification.html.erb
  app/views/notifier_mailer/conclusion_final_review_close_date_warning.html.erb
  app/views/notifier_mailer/conclusion_review_notification.html.erb
  app/views/notifier_mailer/findings_expiration_warning.html.erb
  app/views/notifier_mailer/findings_expired_warning.html.erb
  app/views/notifier_mailer/group_welcome_email.html.erb
  app/views/notifier_mailer/notify_new_finding.html.erb
  app/views/notifier_mailer/notify_new_finding_answer.html.erb
  app/views/notifier_mailer/notify_new_findings.html.erb
  app/views/notifier_mailer/pending_poll_email.html.erb
  app/views/notifier_mailer/reassigned_findings_notification.html.erb
  app/views/notifier_mailer/restore_password.html.erb
  app/views/notifier_mailer/stale_notification.html.erb
  app/views/notifier_mailer/unanswered_finding_to_manager_notification.html.erb
  app/views/notifier_mailer/unanswered_findings_notification.html.erb
  app/views/notifier_mailer/welcome_email.html.erb
  app/views/welcome/audited_index.es.html.erb
  app/views/welcome/auditor_index.es.html.erb
  config/locales/application.es.yml
  config/locales/es.yml
  config/locales/mailer.es.yml
  test/mailers/ldap_mailer_test.rb
Labels: Feature

#73 Ldap Import Async Job
  app/mailers/ldap_mailer.rb
  app/models/concerns/ldap_configs/defaults.rb
  app/models/concerns/ldap_configs/ldap_import.rb
  app/models/concerns/ldap_configs/ldap_service.rb
  app/models/ldap_config.rb
  app/views/ldap_mailer/import_notifier.html.erb
  config/locales/mailer.es.yml
  runners/daily.rb
  test/mailers/ldap_mailer_test.rb
  test/models/ldap_config_test.rb
Labels: Feature

#75 Service user & password are back
  app/views/organizations/_ldap_config.html.erb
  config/locales/models.es.yml
Labels: Feature

#77 Fix sql builder for rails 5.2
  config/initializers/extensions.rb
Labels: migration

#76 Polymorphic "affected by" conversion
  app/controllers/conclusion_final_reviews_controller.rb
  app/mailers/notifier_mailer.rb
  app/models/concerns/polls/about.rb
  app/models/concerns/polls/scopes.rb
  app/models/concerns/users/name.rb
  app/models/poll.rb
  app/pdfs/polls/answer_pdf.rb
  app/views/conclusion_final_reviews/compose_email.html.erb
  app/views/notifier_mailer/pending_poll_email.html.erb
  app/views/polls/_form.html.erb
  app/views/polls/answers/index.html.erb
  app/views/polls/index.html.erb
  app/views/polls/show.html.erb
  config/locales/application.es.yml
  config/locales/es.yml
  config/locales/models.es.yml
  config/locales/views.es.yml
  db/migrate/20180619015853_migrate_poll_affected_user_to_about.rb
  db/schema.rb
  test/controllers/conclusion_final_reviews_controller_test.rb
  test/fixtures/polls.yml
Labels: improvement, migration

#78 Poll about business units
  app/controllers/polls_controller.rb
  app/models/business_unit.rb
  app/models/concerns/polls/validations.rb
  app/views/polls/_form.html.erb
  config/routes.rb
  db/schema.rb
  test/controllers/polls_controller_test.rb
  test/models/poll_test.rb
Labels: Feature

#71 Rails 5.2
  Gemfile
  Gemfile.lock
  app/controllers/conclusion_final_reviews_controller.rb
  app/models/concerns/conclusion_final_reviews/defaults.rb
  app/models/conclusion_final_review.rb
  bin/bundle
  bin/setup
  bin/update
  bin/yarn
  config/application.rb
  config/cable.yml
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_5_2.rb
  config/initializers/sidekiq.rb
  config/storage.yml
  test/models/conclusion_final_review_test.rb
  test/models/conclusion_review_test.rb
  test/models/user_test.rb
Labels: migration

#80 Search findings by updated_at
  app/helpers/application_helper.rb
  app/models/concerns/findings/search.rb
  app/views/findings/index.html.erb
  test/controllers/findings_controller_test.rb
Labels: Feature

#79 Clone Questionnaire
  app/controllers/questionnaires_controller.rb
  app/models/concerns/questionnaires/clone.rb
  app/models/concerns/questionnaires/questions.rb
  app/models/questionnaire.rb
  app/views/questionnaires/index.html.erb
  test/controllers/questionnaires_controller_test.rb
  test/fixtures/answer_options.yml
  test/models/questionnaire_test.rb
Labels: Feature

#81 Performance
  app/models/concerns/findings/csv.rb
  app/models/concerns/findings/follow_up.rb
  app/models/concerns/findings/user_assignments.rb
  app/models/concerns/findings/versions.rb
Labels: improvement
