Repository cirope/mawidabp, pull requests merged in 2018-08, with the labels that each got.

#89 Goodby Irreverent gem
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/flash_responders.rb
  app/models/concerns/groups/current.rb
  app/models/concerns/organizations/current.rb
  lib/application_responder.rb
Labels: Refactor

#90 Good bye Search cop
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/users/searches.rb
  app/models/user.rb
  test/test_helper.rb
Labels: Refactor

#93 Findings brief
  Gemfile.lock
  app/mailers/notifier_mailer.rb
  app/models/concerns/findings/brief.rb
  app/models/concerns/users/scopes.rb
  app/models/finding.rb
  app/views/notifier_mailer/findings_brief.html.erb
  config/initializers/constants.rb
  config/initializers/settings.rb
  config/locales/application.es.yml
  config/locales/views.es.yml
  lib/tasks/db.rake
  runners/daily.rb
  test/mailers/notifier_mailer_test.rb
  test/mailers/previews/notifier_mailer_preview.rb
  test/models/finding_test.rb
Labels: Feature

#91 LDAP Service User
  app/controllers/organizations_controller.rb
  test/controllers/organizations_controller_test.rb
Labels: bug

#92 Migrate from Textile to Markdown
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  app/helpers/markdown_helper.rb
  app/helpers/users/status_helper.rb
  app/mailers/ldap_mailer.rb
  app/mailers/notifier_mailer.rb
  app/models/concerns/users/reassigns.rb
  app/models/concerns/users/releases.rb
  app/views/common_mailer/_footer.html.erb
  app/views/findings/_audited_form.html.erb
  app/views/findings/_auditor_form.html.erb
  app/views/findings/show.html.erb
  app/views/news/_markdown_inline.es.html.erb
  app/views/notifier_mailer/_finding.html.erb
  app/views/notifier_mailer/_task.html.erb
  app/views/notifier_mailer/blank_password_notification.html.erb
  app/views/notifier_mailer/changes_notification.html.erb
  app/views/notifier_mailer/conclusion_review_notification.html.erb
  app/views/notifier_mailer/notify_new_finding_answer.html.erb
  app/views/notifier_mailer/restore_password.html.erb
  app/views/notifier_mailer/unanswered_finding_to_manager_notification.html.erb
  app/views/notifier_mailer/unanswered_findings_notification.html.erb
  app/views/notifier_mailer/welcome_email.html.erb
  app/views/users/status/show.html+graph.erb
  app/views/users/status/show.html.erb
  config/locales/application.es.yml
  config/locales/es.yml
  config/locales/views.es.yml
  test/controllers/conclusion_draft_reviews_controller_test.rb
  test/controllers/conclusion_final_reviews_controller_test.rb
  test/mailers/notifier_mailer_test.rb
Labels: Refactor, migration

#94 Questionnaires un-destroyable with answered polls
  app/controllers/questionnaires_controller.rb
  app/models/concerns/questionnaires/validations.rb
  config/locales/models.es.yml
  test/models/questionnaire_test.rb
Labels: improvement

#95 Findings report with max tags quantity
  app/controllers/concerns/reports/tagged_findings_report.rb
  app/controllers/execution_reports_controller.rb
  app/controllers/follow_up_audit_controller.rb
  app/models/concerns/findings/user_assignments.rb
  app/models/concerns/users/roles.rb
  app/models/role.rb
  app/views/execution_reports/index.html.erb
  app/views/findings/tagged_findings_report.html.erb
  app/views/follow_up_audit/index.html.erb
  app/views/shared/filters/_tags_count.html.erb
  config/locales/application.es.yml
  config/routes.rb
  test/controllers/execution_reports_controller_test.rb
  test/controllers/follow_up_audit_controller_test.rb
Labels: Feature

#96 Tagged findings report mini-fixes + csv export
  app/controllers/concerns/reports/tagged_findings_report.rb
  app/models/concerns/findings/user_assignments.rb
  app/models/concerns/users/roles.rb
  app/models/role.rb
  app/views/execution_reports/tagged_findings_report.html.erb
  app/views/follow_up_audit/tagged_findings_report.html.erb
  app/views/shared/filters/_finding_multiple.html.erb
  app/views/shared/filters/_finding_statuses.html.erb
  app/views/shared/filters/_tags_count.html.erb
  test/controllers/execution_reports_controller_test.rb
  test/controllers/follow_up_audit_controller_test.rb
Labels: Feature, bug
