Repository cirope/mawidabp, pull requests merged in 2018-05, with the labels that each got.

#59 Cambiando ENVs por organization_type
  .travis.yml
  config/application.alternative.yml
  config/application.normal.yml
  config/application.rb
  config/application.reviews_scored_by_weakness.yml
  config/database.yml
Labels: improvement, proposal

#57 Order Findings by readings
  app/controllers/application_controller.rb
  app/controllers/concerns/findings/current_user_scopes.rb
  app/models/concerns/findings/sort_columns.rb
  app/models/concerns/oportunities/sort_columns.rb
  config/locales/views.es.yml
  config/unicorn.rb
Labels: improvement

#58 Acción para recobrar el nombre original del control_objective
  app/controllers/control_objective_items_controller.rb
  app/controllers/reviews_controller.rb
  app/helpers/control_objective_items_helper.rb
  app/models/concerns/control_objective_items/control_objective.rb
  app/views/reviews/_control_objective_item.html.erb
  app/views/reviews/reset_control_objective_name.js.erb
  config/locales/application.es.yml
  config/locales/models.es.yml
  config/routes.rb
  test/controllers/control_objective_items_controller_test.rb
  test/controllers/reviews_controller_test.rb
Labels: improvement

#62 Cipher for encrypt and decrypt data
  lib/security.rb
  test/models/ldap_config_test.rb
Labels: improvement

#63 Ldap ServiceUser for async import
  app/controllers/organizations_controller.rb
  app/models/concerns/ldap_configs/ldap_service.rb
  app/models/concerns/ldap_configs/validation.rb
  app/models/ldap_config.rb
  app/views/organizations/_ldap_config.html.erb
  config/locales/models.es.yml
  config/locales/simple_form.es.yml
  db/migrate/20180521222237_add_service_login_to_ldap_config.rb
  db/schema.rb
  test/models/ldap_config_test.rb
Labels: improvement

#64 Review score details report
  app/controllers/concerns/reports/review_score_details_report.rb
  app/controllers/concerns/reports/review_scores_report.rb
  app/controllers/conclusion_reports_controller.rb
  app/views/conclusion_reports/index.html.erb
  app/views/conclusion_reports/review_score_details_report.html.erb
  app/views/shared/filters/_business_unit_multiple.html.erb
  app/views/shared/filters/_conclusion_and_scope_multiple.html.erb
  config/locales/application.es.yml
  config/locales/es.yml
  config/routes.rb
  test/controllers/conclusion_reports_controller_test.rb
Labels: improvement

#65 Fixing findings order by not readed comments in PDF
  app/models/concerns/findings/sort_columns.rb
  app/pdfs/finding_pdf.rb
  test/controllers/findings_controller_test.rb
Labels: bug

#66 Import user states
  app/controllers/organizations_controller.rb
  app/models/concerns/ldap_configs/ldap_import.rb
  app/models/concerns/users/validations.rb
  app/views/organizations/_ldap_config.html.erb
  app/views/users/imports/create.html.erb
  config/locales/views.es.yml
  test/models/user_test.rb
Labels: improvement, proposal

#67 New review PDF
  app/controllers/reviews_controller.rb
  app/models/concerns/reviews/pdf.rb
  app/models/review.rb
  app/views/reviews/show.html.erb
  config/locales/application.es.yml
  config/locales/es.yml
  test/controllers/reviews_controller_test.rb
  test/models/review_test.rb
Labels: improvement

#69 Unchanged import status
  app/helpers/users/imports_helper.rb
  app/models/concerns/ldap_configs/ldap_import.rb
  app/views/users/imports/create.html.erb
  config/locales/views.es.yml
  test/models/ldap_config_test.rb
Labels: improvement, proposal
