Repository cirope/mawidabp, pull requests merged in 2024-12, with the labels that each got.

#928 Always replace workpaper name with filename
  app/assets/javascripts/work_papers.js
Labels: improvement

#930 Improve history changes show
  app/models/concerns/control_objective_items/history.rb
  app/views/control_objective_items/_history_changes.html.erb
Labels: improvement

#934 Rename finding state names
  config/locales/application.es.yml
  config/locales/mailer.es.yml
  config/locales/models.es.yml
  config/locales/views.es.yml
Labels: improvement

#932 Add readonly logic for review user assignments
  app/models/concerns/reviews/users.rb
  app/views/reviews/_form.html.erb
Labels: feature

#951 Fix I18n in work paper statuses
  config/locales/views.en.yml
  config/locales/views.es.yml
Labels: bug
